### ISSUE TITLE
Risky name choice

### ISSUE THREAD

**Issue by mjurczyk** [RyanMarcus/vulcan#2]
Can be quite easily mistaken with https://www.khronos.org/vulkan :wink:

**Comment by RyanMarcus** [comment]
I suppose it could also be confused with [this](https://www.firebase.com/blog/2014-09-30-vulcan.html) or [this](http://www.maptek.com/products/vulcan/)... Since one is an OpenCL replacement, one a database tool, and the other is 3D data mining software, I think I'm safe. :)

When I thought of the name, there was no turning back -- it seemed too perfect. :)
